"use client";

import dynamic from "next/dynamic";
import Image from "next/image";
import Link from "next/link";
import { Building2, Check, Copy, Flag, Grid3X3, Heart, KeyRound, Mail, MapPin, MessageCircle, Share2, ShieldCheck, Star, Wifi } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useApp } from "@/app/app-provider";
import { Counter, Modal } from "@/components/modal";
import { LoginModal } from "@/components/login-modal";
import { peso, reservationPricing } from "@/lib/finance";
import { listingTypeLabels } from "@/lib/listings";
import type { RentalListing } from "@/lib/types";

const PropertyMap = dynamic(() => import("@/components/property-map").then((module) => module.PropertyMap), { ssr: false, loading: () => <div className="map-shell" /> });
type DetailModal = "gallery" | "share" | "amenities" | "reviews" | "host" | "map" | "price" | "rules" | "report" | "dates" | "renters" | null;

function CalendarMonth({ date, selected }: { date: Date; selected: string }) {
  const year = date.getFullYear();
  const month = date.getMonth();
  const firstDay = new Date(year, month, 1).getDay();
  const days = new Date(year, month + 1, 0).getDate();
  const cells = [...Array(firstDay).fill(null), ...Array.from({ length: days }, (_, index) => index + 1)];
  return <div className="availability-month"><h3>{date.toLocaleDateString("en-PH", { month: "long", year: "numeric" })}</h3><div className="calendar-weekdays">{["S", "M", "T", "W", "T", "F", "S"].map((day, index) => <span key={`${day}-${index}`}>{day}</span>)}</div><div className="calendar-days">{cells.map((day, index) => day ? <span className={new Date(year, month, day).toISOString().slice(0, 10) === selected ? "selected" : ""} key={`${day}-${index}`}>{day}</span> : <span key={`empty-${index}`} />)}</div></div>;
}

export function PropertyDetail({ listing }: { listing: RentalListing }) {
  const { isSaved, showToast } = useApp();
  const [modal, setModal] = useState<DetailModal>(null);
  const [loginOpen, setLoginOpen] = useState(false);
  const galleryRef = useRef<HTMLDivElement>(null);
  const [sectionNavVisible, setSectionNavVisible] = useState(false);
  const [activeSection, setActiveSection] = useState("photos");
  const [moveIn, setMoveIn] = useState(listing.availableFrom);
  const [lease, setLease] = useState(Math.max(12, listing.minimumLeaseMonths));
  const [adults, setAdults] = useState(1); const [children, setChildren] = useState(0); const [pets, setPets] = useState(0);
  const pricing = reservationPricing(listing.monthlyRent);
  const saved = isSaved(listing.id);
  const reserveHref = `/reserve/${listing.slug}?moveIn=${moveIn}&lease=${lease}&adults=${adults}&children=${children}&pets=${pets}`;
  useEffect(() => {
    const gallery = galleryRef.current;
    if (!gallery) return;
    const galleryObserver = new IntersectionObserver(([entry]) => setSectionNavVisible(!entry.isIntersecting && entry.boundingClientRect.bottom < 90), { threshold: 0, rootMargin: "-80px 0px 0px" });
    galleryObserver.observe(gallery);
    const sections = ["photos", "amenities", "reviews", "location"].map((id) => document.getElementById(id)).filter(Boolean) as HTMLElement[];
    const sectionObserver = new IntersectionObserver((entries) => {
      const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top)[0];
      if (visible?.target.id) setActiveSection(visible.target.id);
    }, { rootMargin: "-155px 0px -58% 0px", threshold: [0, .15] });
    sections.forEach((section) => sectionObserver.observe(section));
    return () => { galleryObserver.disconnect(); sectionObserver.disconnect(); };
  }, []);
  const goToSection = (id: string) => { setActiveSection(id); document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const share = async () => { const data = { title: listing.title, text: `Take a look at ${listing.title} on Kubo`, url: window.location.href }; if (navigator.share) await navigator.share(data); else { await navigator.clipboard.writeText(data.url); showToast("Link copied"); } };
  return <><nav className={`detail-section-nav ${sectionNavVisible ? "visible" : ""}`} aria-label="Property sections"><div className="detail-section-nav-inner">{[["photos", "Photos"], ["amenities", "Amenities"], ["reviews", "Reviews"], ["location", "Location"]].map(([id, label]) => <button type="button" className={activeSection === id ? "active" : ""} onClick={() => goToSection(id)} key={id}>{label}</button>)}<div className="detail-nav-reserve"><span><strong>{peso(listing.monthlyRent)}</strong> month<small><Star size={12} fill="currentColor" /> {listing.rating} · {listing.reviewCount} reviews</small></span><Link href={reserveHref} className="button primary">Reserve</Link></div></div></nav><div className="detail-page container">
    <div className="detail-heading"><div><h1>{listing.title}</h1><div className="detail-meta"><span><Star size={14} fill="currentColor" /> {listing.rating}</span><button className="link-button" type="button" onClick={() => setModal("reviews")}>{listing.reviewCount} reviews</button><span>{listing.neighborhood}, {listing.city}</span></div></div><div className="detail-actions"><button type="button" onClick={() => setModal("share")}><Share2 size={17} /><span>Share</span></button><button type="button" onClick={() => setLoginOpen(true)}><Heart size={17} fill={saved ? "currentColor" : "none"} /><span>{saved ? "Saved" : "Save"}</span></button></div></div>
    <div className="gallery-grid" id="photos" ref={galleryRef}>{listing.gallery.map((image, index) => <button type="button" key={image} onClick={() => setModal("gallery")} aria-label={`Open photo ${index + 1}`}><Image src={image} alt={`${listing.title}, photo ${index + 1}`} fill priority={index === 0} sizes={index === 0 ? "60vw" : "25vw"} unoptimized /></button>)}<button type="button" className="show-photos" onClick={() => setModal("gallery")}><Grid3X3 size={17} />Show all photos</button></div>
    <div className="detail-layout"><div className="detail-main">
      <section className="listing-intro"><h2>{listingTypeLabels[listing.type]} in {listing.neighborhood}, {listing.city}</h2><p>{listing.capacity} residents · {listing.bedrooms || "Studio"} bedroom{listing.bedrooms === 1 ? "" : "s"} · {listing.beds} bed{listing.beds === 1 ? "" : "s"} · {listing.bathrooms} bath</p></section>
      <section className="guest-favorite-card"><strong>Guest<br />favorite</strong><span>One of the most loved homes on Kubo, according to renters</span><button type="button" onClick={() => setModal("reviews")}><b>{listing.rating}</b><small>★★★★★</small></button><button type="button" onClick={() => setModal("reviews")}><b>{listing.reviewCount}</b><small>Reviews</small></button></section>
      <section className="host-summary"><button className="host-avatar" type="button" onClick={() => setModal("host")}><Image src={listing.host.avatar} alt={listing.host.name} fill unoptimized /></button><div><h3>Hosted by {listing.host.name}</h3><p>Verified host · {listing.host.yearsHosting} years hosting</p></div></section>
      <section className="highlights"><div className="highlight"><ShieldCheck size={24} /><div><h3>Verified host</h3><p>Identity and contact details are confirmed.</p></div></div><div className="highlight"><KeyRound size={24} /><div><h3>Move-in support</h3><p>The host will help coordinate keys and building access.</p></div></div><div className="highlight"><MapPin size={24} /><div><h3>Connected neighborhood</h3><p>{listing.nearby[0].name} is about {listing.nearby[0].minutes} minutes away.</p></div></div></section>
      <section className="description-section"><p>{listing.description}</p><h3>The space</h3><p>{listing.furnishing === "fully furnished" ? "This furnished home is ready for everyday living, with practical storage and comfortable spaces for work and rest." : "The home offers a flexible layout you can arrange around your own routines and furnishings."}</p></section>
      <section className="sleeping-section"><h2>Where you&apos;ll sleep</h2><article className="sleep-card"><div><Image src={listing.gallery[2] || listing.gallery[0]} alt={`Bedroom at ${listing.title}`} fill unoptimized /></div><h3>{listing.bedrooms > 1 ? "Primary bedroom" : "Bedroom area"}</h3><p>{listing.beds} bed{listing.beds === 1 ? "" : "s"}</p></article></section>
      <section id="amenities"><h2>What this place offers</h2><div className="amenity-grid">{listing.amenities.slice(0, 8).map((amenity) => <div className="amenity-item" key={amenity}>{amenity === "Wi-Fi" ? <Wifi size={21} /> : amenity === "Security" ? <ShieldCheck size={21} /> : amenity === "Air conditioning" ? <Check size={21} /> : <Building2 size={21} />}{amenity}</div>)}</div><button className="button secondary" type="button" onClick={() => setModal("amenities")}>Show all {listing.amenities.length} amenities</button></section>
      <section className="availability-section"><h2>{lease} months in {listing.city}</h2><p>Move in {new Date(moveIn).toLocaleDateString("en-PH", { month: "short", day: "numeric", year: "numeric" })}</p><div className="availability-calendars"><CalendarMonth date={new Date(`${moveIn}T00:00:00`)} selected={moveIn} /><CalendarMonth date={new Date(new Date(`${moveIn}T00:00:00`).getFullYear(), new Date(`${moveIn}T00:00:00`).getMonth() + 1, 1)} selected={moveIn} /></div><button type="button" className="button secondary" onClick={() => setModal("dates")}>Edit move-in and lease</button></section>
    </div><aside className="booking-aside"><button type="button" className="price-assurance" onClick={() => setModal("price")}><span>🏷️</span>Prices include all fees</button><div className="booking-card"><div className="booking-price"><div><strong>{peso(listing.monthlyRent)}</strong> month</div><span><Star size={14} fill="currentColor" />{listing.rating}</span></div><div className="booking-fields"><button type="button" onClick={() => setModal("dates")}><b>Move in</b><span>{new Date(moveIn).toLocaleDateString("en-PH", { month: "short", day: "numeric", year: "numeric" })}</span></button><button type="button" onClick={() => setModal("renters")}><b>Renters</b><span>{adults + children} resident{adults + children === 1 ? "" : "s"}</span></button></div><Link href={reserveHref} className="button primary wide">Reserve</Link><p className="charge-note">You won&apos;t be charged for the full lease today</p><div className="price-lines"><div className="price-line"><button type="button" className="link-button" onClick={() => setModal("price")}>Holding deposit</button><span>{peso(pricing.holdingDeposit)}</span></div><div className="price-line"><button type="button" className="link-button" onClick={() => setModal("price")}>Kubo service fee</button><span>{peso(pricing.serviceFee)}</span></div><div className="price-line price-total"><span>Due today</span><span>{peso(pricing.dueToday)}</span></div></div></div><button type="button" className="report-listing-link" onClick={() => setModal("report")}><Flag size={16} />Report this listing</button></aside></div>
    <div className="detail-after-booking">
      <section id="reviews" className="review-detail-section"><div className="review-hero"><div className="review-laurels"><span>❧</span><b>{listing.rating}</b><span>❧</span></div><h2>Renter favorite</h2><p>This home is a renter favorite based on ratings, reviews, and reliability</p><button type="button" className="link-button" onClick={() => setModal("reviews")}>How reviews work</button></div><div className="rating-dimensions"><div className="rating-bars"><strong>Overall rating</strong>{[5,4,3,2,1].map((score) => <div key={score}><span>{score}</span><i><b style={{ width: `${score === 5 ? 96 : score === 4 ? 32 : 5}%` }} /></i></div>)}</div>{[["Cleanliness", "5.0"], ["Accuracy", "5.0"], ["Move-in", "4.9"], ["Communication", "5.0"], ["Location", "4.8"], ["Value", "4.9"]].map(([label, value]) => <div className="rating-dimension" key={label}><span>{label}</span><b>{value}</b><Star size={22} /></div>)}</div><div className="review-topic-row">{["Neighborhood", "Hospitality", "Comfort", "Indoor spaces", "Value", "Location"].map((topic, index) => <button type="button" key={topic} onClick={() => setModal("reviews")}>{["📍", "🎁", "🛏️", "🛋️", "🏷️", "🗺️"][index]} {topic} <span>{3 + index}</span></button>)}</div><div className="reviews-grid">{listing.reviews.slice(0, 4).map((review) => <article className="review-card" key={review.id}><div className="review-author"><span>{review.author[0]}</span><div><strong>{review.author}</strong><small>{review.date}</small></div></div><div className="review-stars">★★★★★</div><p>{review.text}</p></article>)}</div><button className="button secondary" type="button" onClick={() => setModal("reviews")}>Show all {listing.reviewCount} reviews</button></section>
      <section id="location"><h2>Where you&apos;ll live</h2><p>{listing.neighborhood}, {listing.city}</p><button type="button" className="detail-map" onClick={() => setModal("map")} aria-label="Open full map"><PropertyMap listings={[listing]} selectedId={listing.id} /></button><div className="nearby-grid">{listing.nearby.map((place) => <div className="nearby-card" key={place.name}><strong>{place.name}</strong><small>{place.minutes} minutes · {place.kind}</small></div>)}</div></section>
      <section><h2>House rules</h2><div className="rules-list">{listing.houseRules.slice(0, 3).map((rule) => <div key={rule}>{rule}</div>)}</div><button className="button secondary" type="button" onClick={() => setModal("rules")}>Show all rules</button></section>
      <section className="listing-summary"><div><h2>Meet your host, {listing.host.name}</h2><p>{listing.host.yearsHosting} years hosting · {listing.host.responseRate}% response rate</p></div><button className="button secondary" type="button" onClick={() => setModal("host")}>Host details</button></section>
    </div>
    <LoginModal open={loginOpen} onClose={() => setLoginOpen(false)} />
    <Modal open={modal === "gallery"} onClose={() => setModal(null)} title="Photo tour" fullScreen><div className="gallery-modal-grid">{listing.gallery.map((image, index) => <div key={image}><Image src={image} alt={`${listing.title}, gallery photo ${index + 1}`} fill unoptimized /></div>)}</div></Modal>
    <Modal open={modal === "share"} onClose={() => setModal(null)} title="Share this place"><div className="share-grid"><button type="button" onClick={() => navigator.clipboard.writeText(window.location.href).then(() => showToast("Link copied"))}><Copy size={20} />Copy link</button><button type="button" onClick={share}><Share2 size={20} />Share</button><a href={`mailto:?subject=${encodeURIComponent(listing.title)}&body=${encodeURIComponent("Take a look at this Kubo rental: ")}`}><Mail size={20} />Email</a><button type="button" onClick={() => window.open(`https://www.messenger.com/`, "_blank")}><MessageCircle size={20} />Messenger</button><button type="button" onClick={() => window.open(`viber://forward?text=${encodeURIComponent(listing.title)}`, "_blank")}><MessageCircle size={20} />Viber</button></div></Modal>
    <Modal open={modal === "amenities"} onClose={() => setModal(null)} title="What this place offers"><div className="amenity-grid">{listing.amenities.map((amenity) => <div className="amenity-item" key={amenity}><Check size={20} />{amenity}</div>)}</div></Modal>
    <Modal open={modal === "reviews"} onClose={() => setModal(null)} title={`${listing.rating} · ${listing.reviewCount} reviews`} size="large"><label className="field-block"><span>Search reviews</span><input placeholder="Search by keyword" /></label><div className="reviews-grid">{listing.reviews.concat(listing.reviews).map((review, index) => <article className="review-card" key={`${review.id}-${index}`}><div className="review-author"><span>{review.author[0]}</span><div><strong>{review.author}</strong><small>{review.date}</small></div></div><p>{review.text}</p></article>)}</div></Modal>
    <Modal open={modal === "host"} onClose={() => setModal(null)} title={`About ${listing.host.name}`}><div className="listing-summary"><div><h2>{listing.host.name}</h2><p>Verified host · {listing.host.yearsHosting} years hosting</p></div><div className="host-avatar"><Image src={listing.host.avatar} alt={listing.host.name} fill unoptimized /></div></div><div className="price-lines"><div className="price-line"><span>Response rate</span><strong>{listing.host.responseRate}%</strong></div><div className="price-line"><span>Response time</span><strong>{listing.host.responseTime}</strong></div><div className="price-line"><span>Identity</span><strong>Verified</strong></div></div></Modal>
    <Modal open={modal === "map"} onClose={() => setModal(null)} title={`${listing.neighborhood}, ${listing.city}`} fullScreen><PropertyMap listings={[listing]} selectedId={listing.id} /></Modal>
    <Modal open={modal === "price"} onClose={() => setModal(null)} title="Price details"><div className="price-lines"><div className="price-line"><span>Monthly rent</span><strong>{peso(listing.monthlyRent)}</strong></div><div className="price-line"><span>Holding deposit, credited to first month</span><strong>{peso(pricing.holdingDeposit)}</strong></div><div className="price-line"><span>Kubo service fee</span><strong>{peso(pricing.serviceFee)}</strong></div><div className="price-line price-total"><span>Due today</span><strong>{peso(pricing.dueToday)}</strong></div><div className="price-line"><span>First-month balance due at move-in</span><strong>{peso(pricing.firstMonthBalance)}</strong></div><div className="price-line"><span>Refundable security deposit due at move-in</span><strong>{peso(pricing.securityDeposit)}</strong></div></div></Modal>
    <Modal open={modal === "rules"} onClose={() => setModal(null)} title="House rules"><ul className="rules-list">{listing.houseRules.map((rule) => <li key={rule}>{rule}</li>)}</ul><h3 className="modal-section-title">Cancellation policy</h3><p>Cancel within 48 hours of reserving for a full refund. After that, the holding deposit is refundable until 30 days before move-in, less the service fee.</p></Modal>
    <Modal open={modal === "report"} onClose={() => setModal(null)} title="Report this listing" footer={<button type="button" className="button primary wide" onClick={() => { setModal(null); showToast("Report received. Thank you."); }}>Submit report</button>}><div className="report-options">{["The information is inaccurate", "The listing looks suspicious", "The photos are misleading", "This place is no longer available", "Another concern"].map((reason) => <label key={reason}><input type="radio" name="reason" /> {reason}</label>)}</div></Modal>
    <Modal open={modal === "dates"} onClose={() => setModal(null)} title="Choose your move-in"><label className="field-block"><span>Move-in date</span><input type="date" min={listing.availableFrom} value={moveIn} onChange={(event) => setMoveIn(event.target.value)} /></label><h3 className="modal-section-title">Lease length</h3><div className="lease-grid">{[3,6,12,18,24].filter((months) => months >= listing.minimumLeaseMonths).map((months) => <button type="button" className={lease === months ? "active" : ""} key={months} onClick={() => setLease(months)}><b>{months}</b><span>months</span></button>)}</div></Modal>
    <Modal open={modal === "renters"} onClose={() => setModal(null)} title="Who is moving in?"><Counter label="Adults" helper="Ages 18 or above" min={1} max={listing.capacity} value={adults} onChange={setAdults} /><Counter label="Children" helper="Ages 0 to 17" max={listing.capacity - adults} value={children} onChange={setChildren} /><Counter label="Pets" helper={listing.petsAllowed ? "Pets are welcome" : "This home does not allow pets"} max={listing.petsAllowed ? 3 : 0} value={pets} onChange={setPets} /></Modal>
  </div></>;
}
