"use client";

import dynamic from "next/dynamic";
import Image from "next/image";
import Link from "next/link";
import { Building2, CalendarDays, Check, Copy, Flag, Grid3X3, Heart, Mail, MapPin, MessageCircle, Share2, ShieldCheck, Star, Wifi } from "lucide-react";
import { useState } from "react";
import { useApp } from "@/app/app-provider";
import { Counter, Modal } from "@/components/modal";
import { peso, reservationPricing } from "@/lib/finance";
import { listingTypeLabels } from "@/lib/listings";
import type { RentalListing } from "@/lib/types";

const PropertyMap = dynamic(() => import("@/components/property-map").then((module) => module.PropertyMap), { ssr: false, loading: () => <div className="map-shell" /> });
type DetailModal = "gallery" | "share" | "amenities" | "reviews" | "host" | "map" | "price" | "rules" | "report" | "dates" | "renters" | null;

export function PropertyDetail({ listing }: { listing: RentalListing }) {
  const { isSaved, toggleSaved, showToast } = useApp();
  const [modal, setModal] = useState<DetailModal>(null);
  const [moveIn, setMoveIn] = useState(listing.availableFrom);
  const [lease, setLease] = useState(Math.max(12, listing.minimumLeaseMonths));
  const [adults, setAdults] = useState(1); const [children, setChildren] = useState(0); const [pets, setPets] = useState(0);
  const pricing = reservationPricing(listing.monthlyRent);
  const saved = isSaved(listing.id);
  const reserveHref = `/reserve/${listing.slug}?moveIn=${moveIn}&lease=${lease}&adults=${adults}&children=${children}&pets=${pets}`;
  const share = async () => { const data = { title: listing.title, text: `Take a look at ${listing.title} on Kubo`, url: window.location.href }; if (navigator.share) await navigator.share(data); else { await navigator.clipboard.writeText(data.url); showToast("Link copied"); } };
  return <div className="detail-page container">
    <div className="detail-heading"><div><h1>{listing.title}</h1><div className="detail-meta"><span><Star size={14} fill="currentColor" /> {listing.rating}</span><button className="link-button" type="button" onClick={() => setModal("reviews")}>{listing.reviewCount} reviews</button><span>{listing.neighborhood}, {listing.city}</span></div></div><div className="detail-actions"><button type="button" onClick={() => setModal("share")}><Share2 size={17} /><span>Share</span></button><button type="button" onClick={() => { toggleSaved(listing.id); showToast(saved ? "Removed from wishlists" : "Saved to wishlist"); }}><Heart size={17} fill={saved ? "currentColor" : "none"} /><span>{saved ? "Saved" : "Save"}</span></button></div></div>
    <div className="gallery-grid">{listing.gallery.map((image, index) => <button type="button" key={image} onClick={() => setModal("gallery")} aria-label={`Open photo ${index + 1}`}><Image src={image} alt={`${listing.title}, photo ${index + 1}`} fill priority={index === 0} sizes={index === 0 ? "60vw" : "25vw"} unoptimized /></button>)}<button type="button" className="show-photos" onClick={() => setModal("gallery")}><Grid3X3 size={17} />Show all photos</button></div>
    <div className="detail-layout"><div className="detail-main">
      <section className="listing-summary"><div><h2>{listingTypeLabels[listing.type]} hosted by {listing.host.name}</h2><p>{listing.capacity} residents · {listing.bedrooms || "Studio"} bedroom{listing.bedrooms === 1 ? "" : "s"} · {listing.beds} bed{listing.beds === 1 ? "" : "s"} · {listing.bathrooms} bath</p></div><button className="host-avatar" type="button" onClick={() => setModal("host")}><Image src={listing.host.avatar} alt={listing.host.name} fill unoptimized /></button></section>
      <section className="highlights"><div className="highlight"><ShieldCheck size={24} /><div><h3>Verified host</h3><p>Identity and contact details are confirmed.</p></div></div><div className="highlight"><CalendarDays size={24} /><div><h3>Flexible long-term leasing</h3><p>Stay for {listing.minimumLeaseMonths} months or longer.</p></div></div><div className="highlight"><MapPin size={24} /><div><h3>Connected neighborhood</h3><p>{listing.nearby[0].name} is about {listing.nearby[0].minutes} minutes away.</p></div></div></section>
      <section><p>{listing.description}</p></section>
      <section><h2>What this place offers</h2><div className="amenity-grid">{listing.amenities.slice(0, 8).map((amenity) => <div className="amenity-item" key={amenity}>{amenity === "Wi-Fi" ? <Wifi size={21} /> : amenity === "Security" ? <ShieldCheck size={21} /> : amenity === "Air conditioning" ? <Check size={21} /> : <Building2 size={21} />}{amenity}</div>)}</div><button className="button secondary" type="button" onClick={() => setModal("amenities")}>Show all {listing.amenities.length} amenities</button></section>
      <section><h2>House rules</h2><div className="rules-list">{listing.houseRules.slice(0, 3).map((rule) => <div key={rule}>{rule}</div>)}</div><button className="button secondary" type="button" onClick={() => setModal("rules")}>Show all rules</button></section>
      <section><div className="review-summary"><Star size={22} fill="currentColor" />{listing.rating} · {listing.reviewCount} reviews</div><div className="reviews-grid">{listing.reviews.slice(0, 2).map((review) => <article className="review-card" key={review.id}><div className="review-author"><span>{review.author[0]}</span><div><strong>{review.author}</strong><small>{review.date}</small></div></div><p>{review.text}</p></article>)}</div><button className="button secondary" type="button" onClick={() => setModal("reviews")}>Show all {listing.reviewCount} reviews</button></section>
      <section><h2>Where you&apos;ll live</h2><p>{listing.neighborhood}, {listing.city}</p><button type="button" className="detail-map" onClick={() => setModal("map")} aria-label="Open full map"><PropertyMap listings={[listing]} selectedId={listing.id} /></button><div className="nearby-grid">{listing.nearby.map((place) => <div className="nearby-card" key={place.name}><strong>{place.name}</strong><small>{place.minutes} minutes · {place.kind}</small></div>)}</div></section>
      <section className="listing-summary"><div><h2>Meet your host, {listing.host.name}</h2><p>{listing.host.yearsHosting} years hosting · {listing.host.responseRate}% response rate</p></div><button className="button secondary" type="button" onClick={() => setModal("host")}>Host details</button></section>
      <section><button className="detail-actions" type="button" onClick={() => setModal("report")}><Flag size={17} />Report this listing</button></section>
    </div><aside className="booking-aside"><div className="booking-card"><div className="booking-price"><div><strong>{peso(listing.monthlyRent)}</strong> month</div><span><Star size={14} fill="currentColor" />{listing.rating}</span></div><div className="booking-fields"><button type="button" onClick={() => setModal("dates")}><b>Move in</b><span>{new Date(moveIn).toLocaleDateString("en-PH", { month: "short", day: "numeric", year: "numeric" })}</span></button><button type="button" onClick={() => setModal("renters")}><b>Renters</b><span>{adults + children} resident{adults + children === 1 ? "" : "s"}</span></button></div><Link href={reserveHref} className="button primary wide">Reserve</Link><p className="charge-note">You won&apos;t be charged for the full lease today</p><div className="price-lines"><div className="price-line"><button type="button" className="link-button" onClick={() => setModal("price")}>Holding deposit</button><span>{peso(pricing.holdingDeposit)}</span></div><div className="price-line"><button type="button" className="link-button" onClick={() => setModal("price")}>Kubo service fee</button><span>{peso(pricing.serviceFee)}</span></div><div className="price-line price-total"><span>Due today</span><span>{peso(pricing.dueToday)}</span></div></div></div></aside></div>
    <Modal open={modal === "gallery"} onClose={() => setModal(null)} title="Photo tour" fullScreen><div className="gallery-modal-grid">{listing.gallery.map((image, index) => <div key={image}><Image src={image} alt={`${listing.title}, gallery photo ${index + 1}`} fill unoptimized /></div>)}</div></Modal>
    <Modal open={modal === "share"} onClose={() => setModal(null)} title="Share this place"><div className="share-grid"><button type="button" onClick={() => navigator.clipboard.writeText(window.location.href).then(() => showToast("Link copied"))}><Copy size={20} />Copy link</button><button type="button" onClick={share}><Share2 size={20} />Share</button><a href={`mailto:?subject=${encodeURIComponent(listing.title)}&body=${encodeURIComponent("Take a look at this Kubo rental: ")}`}><Mail size={20} />Email</a><button type="button" onClick={() => window.open(`https://www.messenger.com/`, "_blank")}><MessageCircle size={20} />Messenger</button><button type="button" onClick={() => window.open(`viber://forward?text=${encodeURIComponent(listing.title)}`, "_blank")}><MessageCircle size={20} />Viber</button></div></Modal>
    <Modal open={modal === "amenities"} onClose={() => setModal(null)} title="What this place offers"><div className="amenity-grid">{listing.amenities.map((amenity) => <div className="amenity-item" key={amenity}><Check size={20} />{amenity}</div>)}</div></Modal>
    <Modal open={modal === "reviews"} onClose={() => setModal(null)} title={`${listing.rating} · ${listing.reviewCount} reviews`} size="large"><label className="field-block"><span>Search reviews</span><input placeholder="Search by keyword" /></label><div className="reviews-grid">{listing.reviews.concat(listing.reviews).map((review, index) => <article className="review-card" key={`${review.id}-${index}`}><div className="review-author"><span>{review.author[0]}</span><div><strong>{review.author}</strong><small>{review.date}</small></div></div><p>{review.text}</p></article>)}</div></Modal>
    <Modal open={modal === "host"} onClose={() => setModal(null)} title={`About ${listing.host.name}`}><div className="listing-summary"><div><h2>{listing.host.name}</h2><p>Verified host · {listing.host.yearsHosting} years hosting</p></div><div className="host-avatar"><Image src={listing.host.avatar} alt={listing.host.name} fill unoptimized /></div></div><div className="price-lines"><div className="price-line"><span>Response rate</span><strong>{listing.host.responseRate}%</strong></div><div className="price-line"><span>Response time</span><strong>{listing.host.responseTime}</strong></div><div className="price-line"><span>Identity</span><strong>Verified</strong></div></div></Modal>
    <Modal open={modal === "map"} onClose={() => setModal(null)} title={`${listing.neighborhood}, ${listing.city}`} fullScreen><PropertyMap listings={[listing]} selectedId={listing.id} /></Modal>
    <Modal open={modal === "price"} onClose={() => setModal(null)} title="Price details"><div className="price-lines"><div className="price-line"><span>Monthly rent</span><strong>{peso(listing.monthlyRent)}</strong></div><div className="price-line"><span>Holding deposit, credited to first month</span><strong>{peso(pricing.holdingDeposit)}</strong></div><div className="price-line"><span>Kubo service fee</span><strong>{peso(pricing.serviceFee)}</strong></div><div className="price-line price-total"><span>Due today</span><strong>{peso(pricing.dueToday)}</strong></div><div className="price-line"><span>First-month balance due at move-in</span><strong>{peso(pricing.firstMonthBalance)}</strong></div><div className="price-line"><span>Refundable security deposit due at move-in</span><strong>{peso(pricing.securityDeposit)}</strong></div></div></Modal>
    <Modal open={modal === "rules"} onClose={() => setModal(null)} title="House rules"><ul className="rules-list">{listing.houseRules.map((rule) => <li key={rule}>{rule}</li>)}</ul><h3 className="modal-section-title">Cancellation policy</h3><p>Cancel within 48 hours of reserving for a full refund. After that, the holding deposit is refundable until 30 days before move-in, less the service fee.</p></Modal>
    <Modal open={modal === "report"} onClose={() => setModal(null)} title="Report this listing" footer={<button type="button" className="button primary wide" onClick={() => { setModal(null); showToast("Report received. Thank you."); }}>Submit report</button>}><div className="report-options">{["The information is inaccurate", "The listing looks suspicious", "The photos are misleading", "This place is no longer available", "Another concern"].map((reason) => <label key={reason}><input type="radio" name="reason" /> {reason}</label>)}</div></Modal>
    <Modal open={modal === "dates"} onClose={() => setModal(null)} title="Choose your move-in"><label className="field-block"><span>Move-in date</span><input type="date" min={listing.availableFrom} value={moveIn} onChange={(event) => setMoveIn(event.target.value)} /></label><h3 className="modal-section-title">Lease length</h3><div className="lease-grid">{[3,6,12,18,24].filter((months) => months >= listing.minimumLeaseMonths).map((months) => <button type="button" className={lease === months ? "active" : ""} key={months} onClick={() => setLease(months)}><b>{months}</b><span>months</span></button>)}</div></Modal>
    <Modal open={modal === "renters"} onClose={() => setModal(null)} title="Who is moving in?"><Counter label="Adults" helper="Ages 18 or above" min={1} max={listing.capacity} value={adults} onChange={setAdults} /><Counter label="Children" helper="Ages 0 to 17" max={listing.capacity - adults} value={children} onChange={setChildren} /><Counter label="Pets" helper={listing.petsAllowed ? "Pets are welcome" : "This home does not allow pets"} max={listing.petsAllowed ? 3 : 0} value={pets} onChange={setPets} /></Modal>
  </div>;
}
