"use client";

import Image from "next/image";
import { ArrowLeft, CreditCard, LockKeyhole, Star } from "lucide-react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { useApp } from "@/app/app-provider";
import { Modal } from "@/components/modal";
import { peso, reservationPricing } from "@/lib/finance";
import type { RentalListing } from "@/lib/types";

export function ReservationCheckout({ listing }: { listing: RentalListing }) {
  const params = useSearchParams(); const router = useRouter(); const { addReservation } = useApp();
  const [moveIn, setMoveIn] = useState(params.get("moveIn") || listing.availableFrom); const [lease, setLease] = useState(Number(params.get("lease")) || 12); const [editor, setEditor] = useState<"dates" | "renters" | "policy" | null>(null); const [submitting, setSubmitting] = useState(false);
  const adults = Number(params.get("adults")) || 1; const children = Number(params.get("children")) || 0; const pets = Number(params.get("pets")) || 0; const pricing = reservationPricing(listing.monthlyRent);
  const confirm = () => { setSubmitting(true); const reservation = { id: `KBR-${listing.id}-${moveIn}-${lease}`.replaceAll("-", ""), listingId: listing.id, moveIn, leaseMonths: lease, adults, children, pets, holdingDeposit: pricing.holdingDeposit, serviceFee: pricing.serviceFee, amountPaid: pricing.dueToday, status: "confirmed" as const, createdAt: `${moveIn}T00:00:00.000Z` }; addReservation(reservation); router.push(`/trips/${reservation.id}`); };
  return <div className="checkout-layout container"><div><div className="checkout-title"><Link className="round-button" href={`/properties/${listing.slug}`} aria-label="Back to listing"><ArrowLeft size={22} /></Link><h1>Confirm and reserve</h1></div><section className="checkout-section"><h2>Your stay</h2><div className="checkout-section-row"><div><strong>Move-in and lease</strong><p>{new Date(moveIn).toLocaleDateString("en-PH", { month: "long", day: "numeric", year: "numeric" })} · {lease} months</p></div><button type="button" onClick={() => setEditor("dates")}>Edit</button></div><div className="checkout-section-row"><div><strong>Renters</strong><p>{adults + children} resident{adults + children === 1 ? "" : "s"}{pets ? ` · ${pets} pet${pets === 1 ? "" : "s"}` : ""}</p></div><button type="button" onClick={() => setEditor("renters")}>Edit</button></div></section><section className="checkout-section"><h2>Pay with</h2><div className="payment-card"><div><CreditCard size={24} /><strong>Visa ending in 4242</strong></div><span>Expires 08/30</span></div></section><section className="checkout-section"><h2>Cancellation policy</h2><p>Free cancellation within 48 hours. After that, the holding deposit is refundable until 30 days before move-in, less the service fee.</p><button className="link-button" type="button" onClick={() => setEditor("policy")}>Learn more</button></section><section className="checkout-section"><h2>Ground rules</h2><p>We ask every resident to follow the house rules, keep the property in good condition, and communicate promptly with the host.</p></section><button type="button" className="button primary" onClick={confirm} disabled={submitting}><LockKeyhole size={17} />{submitting ? "Confirming" : `Confirm and pay ${peso(pricing.dueToday)}`}</button></div>
    <aside><div className="reservation-summary"><div className="summary-listing"><div className="summary-image"><Image src={listing.gallery[0]} alt={listing.title} fill unoptimized /></div><div><small>{listing.type}</small><h2>{listing.title}</h2><p><Star size={13} fill="currentColor" /> {listing.rating} ({listing.reviewCount} reviews)</p></div></div><h2 className="modal-section-title">Price details</h2><div className="price-lines"><div className="price-line"><span>Holding deposit</span><span>{peso(pricing.holdingDeposit)}</span></div><div className="price-line"><span>Kubo service fee</span><span>{peso(pricing.serviceFee)}</span></div><div className="price-line price-total"><span>Due today</span><span>{peso(pricing.dueToday)}</span></div><div className="price-line"><span>Due at move-in</span><span>{peso(pricing.dueAtMoveIn)}</span></div></div></div></aside>
    <Modal open={editor === "dates"} onClose={() => setEditor(null)} title="Edit move-in and lease" footer={<button type="button" className="button primary wide" onClick={() => setEditor(null)}>Save</button>}><label className="field-block"><span>Move-in date</span><input type="date" value={moveIn} min={listing.availableFrom} onChange={(event) => setMoveIn(event.target.value)} /></label><div className="lease-grid">{[3,6,12,18,24].filter((months) => months >= listing.minimumLeaseMonths).map((months) => <button type="button" key={months} className={lease === months ? "active" : ""} onClick={() => setLease(months)}><b>{months}</b><span>months</span></button>)}</div></Modal>
    <Modal open={editor === "renters"} onClose={() => setEditor(null)} title="Renters"><p>This reservation is for {adults + children} residents{pets ? ` and ${pets} pets` : ""}. Return to the listing to change occupancy.</p></Modal>
    <Modal open={editor === "policy"} onClose={() => setEditor(null)} title="Cancellation policy"><p>Cancel within 48 hours of reserving for a full refund. After 48 hours, the Kubo service fee is non-refundable. The holding deposit remains refundable until 30 days before move-in.</p><p>For cancellations within 30 days of move-in, the host may retain the holding deposit to cover the reserved period.</p></Modal>
  </div>;
}
