"use client";

import Image from "next/image";
import Link from "next/link";
import { CalendarCheck } from "lucide-react";
import { useApp } from "@/app/app-provider";
import { listings } from "@/lib/listings";

export function TripsPage() { const { reservations } = useApp(); return <div className="container"><div className="page-title"><h1>Trips</h1><p>Your confirmed homes and move-in details.</p></div>{reservations.length ? <div className="trip-grid">{reservations.map((reservation) => { const listing = listings.find((item) => item.id === reservation.listingId); if (!listing) return null; return <Link href={`/trips/${reservation.id}`} className="trip-card" key={reservation.id}><div className="trip-card-photo"><Image src={listing.gallery[0]} alt={listing.title} fill unoptimized /></div><div className="trip-card-copy"><span className="status-pill">Confirmed</span><h2>{listing.title}</h2><p>{new Date(reservation.moveIn).toLocaleDateString("en-PH", { month: "long", day: "numeric", year: "numeric" })}</p></div></Link>; })}</div> : <div className="empty-state"><CalendarCheck size={48} /><h2>No trips booked yet</h2><p>When you reserve a place, your move-in details will appear here.</p><Link className="button primary" href="/properties">Start exploring</Link></div>}</div>; }

export function TripDetail({ id }: { id: string }) { const { reservations } = useApp(); const reservation = reservations.find((item) => item.id === id); const listing = reservation ? listings.find((item) => item.id === reservation.listingId) : null; if (!reservation || !listing) return <div className="empty-state"><h1>Reservation not found</h1><Link className="button primary" href="/trips">Back to trips</Link></div>; return <div className="narrow"><div className="page-title"><span className="status-pill">Confirmed</span><h1>You are moving to {listing.neighborhood}</h1><p>Your host has received your reservation.</p></div><div className="trip-card"><div className="trip-card-photo"><Image src={listing.gallery[0]} alt={listing.title} fill unoptimized /></div><div className="trip-card-copy"><h2>{listing.title}</h2><div className="price-lines"><div className="price-line"><span>Move-in</span><strong>{new Date(reservation.moveIn).toLocaleDateString("en-PH", { month: "long", day: "numeric", year: "numeric" })}</strong></div><div className="price-line"><span>Lease</span><strong>{reservation.leaseMonths} months</strong></div><div className="price-line"><span>Residents</span><strong>{reservation.adults + reservation.children}</strong></div><div className="price-line"><span>Confirmation</span><strong>{reservation.id}</strong></div></div><Link className="button secondary wide" href={`/properties/${listing.slug}`}>View rental</Link></div></div></div>; }
